###############################################
# [directory] (main): <command>               #
###############################################

format = """
$directory\
($git_branch)\
"""

[directory]
format = '[\[$path\]](fg:#56B6C2) '
truncation_length = 1

[git_branch]
format = '[\($branch\): ](fg:#D0666F)'
