###############################################
# [directory] (main): <command>               #
###############################################

format = """
$directory\
($git_branch)\
"""

[directory]
format = '[\[$path\]](fg:#83a598) '
truncation_length = 1

[git_branch]
format = '[\($branch\): ](fg:#d3869b)'
