# bg #394260
# fg #3ec669
# fg #ff9248

format = """
[ţéÂ](#394260)\
[ţŚ┐](fg:#3ec669 bg:#394260)\
$directory\
[ţé┤ ](#394260)\

([ ţéÂ](#394260)\
$git_branch\
$git_status\
[ţé┤](#394260))\

([ ţéÂ](#394260)\
$nodejs\
$golang\
$rust\
$lua\
$c\
[ţé┤](#394260))\
\n$character"""


[character]
success_symbol = '[´üí](bold #3ec669) '
error_symbol = '[´üí](bold #ff9248) '

[directory]
style = "fg:#3ec669 bg:#394260"
format = "[ $path]($style)"
use_os_path_sep = false
truncation_symbol = "../../"
truncation_length = 3

[git_branch]
symbol = "´Éś"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#ff9248 bg:#394260)]($style)'

[git_status]
modified = "´üÇ"
deleted = "´Ü┐"
format = "[( $modified $deleted)](fg:#ff9248 bg:#394260)"

[nodejs]
symbol = "ţťś"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

[rust]
symbol = "ţ×Ę"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

[lua]
symbol = "ţśá"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

[golang]
symbol = "´│Ĺ"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

[vlang]
symbol = "ÔłĘ"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

[c]
symbol = "ţÖë"
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#4885ff bg:#394260)]($style)'

